// capitulo-00-react-angular/src/components/BasicInfo/BasicInfo.tsx
import Avatar from '@mui/material/Avatar';
import Grid from '@mui/material/Grid';


interface BasicInfoProps {
  name: string;
  email: string;
  linkedinUrl: string;
  gitUrl: string;
  photoUrl:string;
}

const BasicInfo: React.FC<BasicInfoProps> = ({ name, email, linkedinUrl, gitUrl,photoUrl }) => {
  return (
      <Grid container spacing={2} alignItems="center"> {/* Use Grid container */}
        <Grid item xs={12} sm={4}> {/* Avatar column */}
          <Avatar
            alt={name}
            src={photoUrl} 
            sx={{ width: 150, height: 150 }} 
          />
        </Grid>
        <Grid item xs={12} sm={8}> {/* Info column */}
          <h2>{name}</h2>
          <p><a href={`mailto:${email}`}>{email}</a></p>
          <p><a href={linkedinUrl} target="_blank" rel="noopener noreferrer">LinkedIn</a></p>
          <p><a href={gitUrl} target="_blank" rel="noopener noreferrer">Github</a></p>
        </Grid>
      </Grid>
    );  
};

export default BasicInfo;

// 01-angular/src/app/components/basic-info/basic-info.component.ts
import { Component,Input } from '@angular/core';
import { MatCardModule } from '@angular/material/card'; 
import { MatGridListModule } from '@angular/material/grid-list'; 
import { MatListModule } from '@angular/material/list'; 

@Component({
  selector: 'app-basic-info',
  standalone: true,
  imports: [
    MatCardModule,
    MatGridListModule,
    MatListModule
  ],
  templateUrl: './basic-info.component.html',
  styleUrl: './basic-info.component.scss'
})

export class BasicInfoComponent {
  @Input() name!: string;
  @Input() email!: string;
  @Input() linkedinUrl!: string;
  @Input() gitUrl!: string;
  @Input() photoUrl!: string;
}


<!-- basic-info.component.html -->
<mat-card>
    <mat-grid-list cols="2" rowHeight="2:1">
        <mat-grid-tile>
            <img class="photo" [src]="photoUrl" [alt]="name" />
        </mat-grid-tile>

        <mat-grid-tile class="info">
            <mat-list>
              <mat-list-item>
                <a [href]="'mailto:' + email">{{ email }}</a>
              </mat-list-item>
              <mat-list-item>
                <a [href]="linkedinUrl" target="_blank">LinkedIn</a>
              </mat-list-item>
              <mat-list-item>
                <a [href]="gitUrl" target="_blank">Github</a>
              </mat-list-item>
            </mat-list>
          </mat-grid-tile>
          

    </mat-grid-list>
</mat-card>
