// capitulo-00-react-angular/src/App.tsx
import BasicInfo from './components/BasicInfo/BasicInfo';
import CertificatesSection from './components/CertificatesSection/CertificatesSection';

import Grid from '@mui/material/Grid';

function App() {
  return (
    <Grid container spacing={2} justifyContent="space-between"> 
      <Grid item xs={12} sm={6}> 
        <BasicInfo
          name="Julian Gamboa"
          email="julian.gamboa.ms.2021@gmail.com"
          linkedinUrl="https://www.linkedin.com/in/julian-gamboa-bahia/"
          gitUrl="https://github.com/julian-gamboa-ensino/"
          photoUrl="https://avatars.githubusercontent.com/u/35019237?v=4"
        />
      </Grid>
      <Grid item xs={12} sm={3}> {/* Use the same width as the first column */}
        <CertificatesSection />
      </Grid>
    </Grid>
  );
}

export default App;

// capitulo-01-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';

import { BasicInfoComponent } from "./components/basic-info/basic-info.component";
import { AllCertificatesComponent } from './components/certificates-section/all-certificates/all-certificates.component';
import { BootcampCertificatesComponent } from './components/certificates-section/bootcamp-certificates/bootcamp-certificates.component';
import { CertificatesSectionComponent } from './components/certificates-section/certificates-section.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    RouterOutlet, 
    BasicInfoComponent,
    AllCertificatesComponent,
    BootcampCertificatesComponent,
    CertificatesSectionComponent,
    
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'Setembro 12';
}
<div class="container">
    <div class="row">
      <div class="col">
        <app-basic-info
          name="Julian Gamboa"
          email="julian.gamboa.ms.2021@gmail.com"
          linkedinUrl="https://www.linkedin.com/in/julian-gamboa-bahia/"
          gitUrl="https://github.com/julian-gamboa-ensino/"
          photoUrl="https://avatars.githubusercontent.com/u/35019237?v=4"
        ></app-basic-info>
      </div>
      <div class="col">
        <app-certificates-section></app-certificates-section>
      </div>
    </div>
  </div>
